server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/accounts/**
              filters:
                - RewritePath=/account-service/(?<segment>.*), /${segment}
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/order-service/(?<segment>.*), /${segment}
            - id: orchid-service
              uri: lb://orchid-service
              predicates:
                - Path=/api/orchids/**
              filters:
                - RewritePath=/orchid-service/(?<segment>.*), /${segment}

# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    # Configuration for Swagger UI Services
    urls:
      - name: Account Service
        url: /account-service/v3/api-docs
      - name: Orchid service
        url: /orchid-service/v3/api-docs
      - name: Order service
        url: /order-service/v3/api-docs
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:0pQYYepE82DkALnEVhAfZREPeHmtHz3z}
    csrf:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG