spring:
  application:
    name: brand-service

  profiles:
    active: test

server:
  port: 4005

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs