api:
  prefix: /api/v1

server:
  port: 8080

spring:
  application:
    name: orchidbe

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb+srv://hoangclw:aDM2LxkZuiR94ly3@crud.u3idzpf.mongodb.net/orchidbe?retryWrites=true&w=majority&appName=Crud
      auto-index-creation: true

  # Disable JPA
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging configuration
logging:
  level:
    org.springframework.data.mongodb: ${MONGO_LOG_LEVEL:INFO}
    org.mongodb.driver: ${MONGO_DRIVER_LOG_LEVEL:WARN}
