spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${SQL_SERVER_HOST}:${SQL_SERVER_PORT};databaseName=Sum2025BlindBoxesDB;trustServerCertificate=true
    username: ${SQL_SERVER_USER}
    password: ${SQL_SERVER_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true