server:
  port: 8080

spring:
  application:
    name: be-pe

  profiles:
    active: test

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
#    doc-expansion: none
    enabled: true
    path: /swagger-ui.html

jwt:
  expiration: ${JWT_EXPIRATION} #1 day = 1 * 24 * 60 * 60
  secretKey: ${JWT_SECRET_KEY}