services:
  be:
    container_name: orchidbe
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "4007:8080"
    networks:
      - sba

networks:
  sba:
    driver: bridge