services:
  be:
    container_name: orchidbe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./stores:/stores
    networks:
      - sba

networks:
  sba:
    driver: bridge