server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost  # Use the hostname from docker-compose
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # URL for the Eureka server


#health check
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF