api:
  prefix: /api/v1

spring:
  application:
    name: orchidbe

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@${MONGO_DB_HOST}/${MONGO_DB_NAME}?authSource=admin
      auto-index-creation: true

  # Disable JPA
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging configuration

jwt:
  expiration: ${JWT_EXPIRATION} #1 day = 1 * 24 * 60 * 60
  expiration-refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION} #60 days = 60 * 24 * 60 * 60
  secretKey: ${JWT_SECRET_KEY}