api:
  prefix: /api/v1

spring:
  application:
    name: orchidbe

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://root:example@zimacube.tail21fc44.ts.net:27017/orchidbe?authSource=admin
      auto-index-creation: true

  # Disable JPA
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging configuration

jwt:
  expiration: 86400 #1 day = 1 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: 刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌