api:
  prefix: /api/v1

spring:
  application:
    name: orchidbe

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=OrchidBE;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Logging configuration

jwt:
  expiration: 86400 #1 day = 1 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: 刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌刘高煌