api:
  prefix: /api/v1

spring:
  application:
    name: orchidbe

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@${MONGO_DB_HOST}/${MONGO_DB_NAME}?authSource=admin
      auto-index-creation: true

  # Disable JPA
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging configuration
logging:
  level:
    org.springframework.data.mongodb: ${MONGO_LOG_LEVEL:INFO}
    org.mongodb.driver: ${MONGO_DRIVER_LOG_LEVEL:WARN}